# Generated by Django 6.0.1 on 2026-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('claimed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('found_in', models.CharField(max_length=200)),
                ('found_by', models.CharField(blank=True, max_length=200, null=True)),
                ('date_found', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
            ],
        ),
    ]
