# Generated by Django 6.0.1 on 2026-03-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitem',
            old_name='found_by',
            new_name='lost_by',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='found_in',
            new_name='lost_in',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='date_found',
        ),
        migrations.AddField(
            model_name='founditem',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='found_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='found_in',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='date_lost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='founditems/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lostitems/'),
        ),
    ]
