# Generated by Django 6.0.3 on 2026-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_found_by_lostitem_lost_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Claimed', 'Claimed')], default='Unclaimed', max_length=20),
        ),
    ]
